command:
  - node
  - server/index.js
env:
  - name: DATABRICKS_HOST
    value: https://fe-sandbox-serverless-9thezy.cloud.databricks.com
  - name: DATABRICKS_CHAT_ENDPOINT
    value: databricks-claude-haiku-4-5
  - name: LAKEBASE_PG_HOST
    value: ep-red-waterfall-d295u8ea.database.us-east-1.cloud.databricks.com
  - name: LAKEBASE_PG_DATABASE
    value: databricks_postgres
  - name: LAKEBASE_PG_USER
    value: ankit.yadav@databricks.com
