command:
  - node
  - server/index.js
env:
  - name: DATABRICKS_HOST
    value: https://fevm-ay-demo-workspace.cloud.databricks.com
  - name: DATABRICKS_CHAT_ENDPOINT
    value: databricks-claude-haiku-4-5
  - name: LAKEBASE_PG_HOST
    value: ep-steep-rice-d2fci9kw.database.us-east-1.cloud.databricks.com
  - name: LAKEBASE_PG_DATABASE
    value: databricks_postgres
  - name: LAKEBASE_PG_USER
    value: ankit.yadav@databricks.com
